kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: apt-cacher-ng
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
