apiVersion: v1
kind: Service
metadata:
  name: pebble-ext
  labels:
    name: pebble
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 32443
      protocol: TCP
      name: https
    - port: 8443
      targetPort: 32443
      protocol: TCP
      name: https2
    - port: 8444
      targetPort: 32444
      protocol: TCP
      name: https4
  selector:
    app.kubernetes.io/instance: pebble
    app.kubernetes.io/name: pebble
