apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nfs-provisioner
resources:
  - namespace.yaml
  - storageclass-archived.yaml
  - storageclass-not-archived.yaml
  - storageclass-not-archived-retained.yaml
