apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storeage-not-archived
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nas.crylle.local/nfs  # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
