apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storeage-archived-retained
provisioner: nas.crylle.local/nfs  # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "true"
reclaimPolicy: "Retain"
