# patch_nfs_details.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: PROVISIONER_NAME
              value: nas.crylle.local/nfs
            - name: NFS_SERVER
              value: 192.168.1.239
            - name: NFS_PATH
              value: /srv/nfs/share
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.1.239
            path: /srv/nfs/share
